package com.fraud.domain

case class RawCredentialsScheme(
                                 Time: Double,
                                 V1: Double,
                                 V2: Double,
                                 V3: Double,
                                 V4: Double,
                                 V5: Double,
                                 V6: Double,
                                 V7: Double,
                                 V8: Double,
                                 V9: Double,
                                 V10: Double,
                                 V11: Double,
                                 V12: Double,
                                 V13: Double,
                                 V14: Double,
                                 V15: Double,
                                 V16: Double,
                                 V17: Double,
                                 V18: Double,
                                 V19: Double,
                                 V20: Double,
                                 V21: Double,
                                 V22: Double,
                                 V23: Double,
                                 V24: Double,
                                 V25: Double,
                                 V26: Double,
                                 V27: Double,
                                 V28: Double,
                                 Amount: Double,
                                 Class: String,
                               )
